name: Example of Sequential jobs

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: greet sportsbet
        run: echo "Hello Sportsbet"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: hunger check
        run: echo "Are you hungry?"

  job-3:
    if: ${{ always() }}
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
      - name: serve lunch
        run: echo "Food is served"
